# 对话昵称
NickName: 小七

# 对话仅限主人可用
OnlyMaster: false

# 必应开关
EnableBing: false

# 必应参数
BingCookie: ""

#语音开关
EnableVoice: false

#艾特开关
EnableAt: false

#发音人
VoiceIndex: 23

#AI数据 Mirror
MirrorBearer: ""
MirrorConversationId: ""

#主人名字
Master: 止水
#主人QQ
MasterQQ: 172679743

#必应模型   默认：balanced, 创意：creative, 精确：precise, 快速：fast
toneStyle: "creative"

#链接模式
LinkMode: false

#对话接口地址
OpenAiApiUrl: "https://api.openai.com/v1/chat/completions"

#对话秘钥
OpenAiApiKey: ""

#对话模型
OpenAiModel: "gpt-4o-mini"

#对话历史最大长度
OpenAiMaxHistory: 20
