# 对话昵称
NickName: 小七

# 对话仅限主人可用
OnlyMaster: false

# 必应开关
EnableBing: false

# 必应参数
BingCookie: ""

#语音开关
EnableVoice: false

#发音人
VoiceIndex: 23

#AI数据 Mirror
MirrorBearer: ""
MirrorConversationId: ""

#主人名字
Master: 止水
#主人QQ
MasterQQ: 172679743

